# 此工作流程用于将项目部署到 GitHub Pages。
# 当 `main` 分支有新的推送时，或者手动从 GitHub Actions 选项卡触发时，工作流程将自动运行。

name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # 仅在 `main` 分支有推送时触发

  # 允许你从 Actions 选项卡手动运行此工作流程
  workflow_dispatch:

# 设置 GITHUB_TOKEN 的权限，以允许部署到 GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest # 使用最新的 Ubuntu 环境运行任务

    steps:
      # 检出代码到工作目录
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 pnpm 包管理器，并指定版本为 9
      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      # 设置 Node.js 环境，并指定版本为 20
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 安装项目依赖
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # 构建 UI
      - name: Build UI
        run: pnpm run ui-devops:build

      # 使用 VitePress 构建文档
      - name: Build project
        run: pnpm run docs:build

      # 将构建后的文档部署到 GitHub Pages
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # 使用 GitHub Token 进行身份验证
          branch: gh-pages # 部署到 `gh-pages` 分支
          folder: docs/.vitepress/dist # 指定要部署的文件夹路径
